### PR TITLE
Support for OpenCV 2.4.9

### PR DESCRIPTION
**Pull request by cameronehrlich**
Updated submodule, framework, and Podspec for OpenCV 2.4.9

### CODE REVIEW

**Comment by allenhumphreys** [comment]
Please complete this!

**Comment by cameronehrlich** [comment]
It should be ready to go, they just need to pull it!

**Comment by allenhumphreys** [comment]
Where have all the contributors gone?

**Comment by cameronehrlich** [comment]
Good question.  I did this because we needed it at the company I was working for back then.  I am surprised that this hasn't been at least responded to yet!

**Comment by allenhumphreys** [comment]
I agree, I'm working with the person who took over the podspec to try to get it working correctly. He made changes that broke other things.

Allen Humphreys
iOS App Developer

www.360fly.com
Mobile: +1 (260) 704-3527
LinkedIn https://www.linkedin.com/pub/allen-humphreys/53/b99/633

**Comment by cameronehrlich** [comment]
Let me know if I can help!

**Comment by allenhumphreys** [comment]
Are you a wiz with pod specs?

Allen Humphreys
iOS App Developer

www.360fly.com
Mobile: +1 (260) 704-3527
LinkedIn https://www.linkedin.com/pub/allen-humphreys/53/b99/633

**Comment by cameronehrlich** [comment]
Not particularly, but what's the problem we're facing?

**Comment by ExoticObjects** [comment]
I can get to this on Tuesday - trying to make a deadline.

FWIW, I don't know what's up with contributors on this project. I AM one,
but only by accident. I was given commit privileges after making a few
comments on other commits. I'm not sure who's in charge, if anyone...

On Sun, Oct 12, 2014 at 3:00 PM, Cameron Ehrlich notifications@github.com
wrote:

> Not particularly, but what's the problem we're facing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fl0p/OpenCV-iOS/pull/12#issuecomment-58816719.

## 

Jim Kremens
Co-Founder, Exotic Objects
M:917-885-1734
O:212-918-2025

**Comment by allenhumphreys** [comment]
Just so you know, the pod `OpenCV` has since been claimed by another person and no one other than him will be able to publish an updated spec. I'm going to try to convince him to use his spec on this repo because the spec is currently pulling files from source forge which is very slow compared to Git.

Hopefully, within a day or 2 we'll have this all straightened out.

**Comment by cameronehrlich** [comment]
Hello from the future!

**Pull request closed without merging**
